---  
- hosts: localhost      
  connection: local  
  gather_facts: no    
  vars:  
    region: us-east-1    
  tasks:  
    - name: launch ec2 instance
      ec2:
        region: "{{ region }}"  
        key_name: devops-ansible.pem
        instance_type: t2.micro  
        image: ami-b63769a1  
        wait: yes    
        group: your-aws-group
      register: ec2  
    - name: associate new EIP for the instance    
      ec2_eip:
        region: "{{ region }}"
        instance_id: "{{ item.id }}"
      with_items: ec2.instances
